/**
 * Consultant specialty catalog — categories with specialties (sub-items).
 *
 * Stored value is the specialty string (e.g. "Cardiologist").
 */

export const SPECIALTY_CATEGORIES = [
  {
    category: 'General & Family Practice',
    specialties: [
      'General Physician',
      'General Practitioner',
      'Family Medicine',
      'Family Physician',
      'Internal Medicine',
      'Primary Care Physician',
      'Hospital Medicine',
      'Hospitalist',
      'Emergency Medicine',
      'Urgent Care Medicine',
      'Geriatric Medicine',
      'Adolescent Medicine',
      'Preventive Medicine',
      'Community Medicine',
      'Lifestyle Medicine',
      'Travel Medicine',
      'Occupational Medicine',
      'Aerospace Medicine',
      'Rural Medicine',
    ],
  },

  {
    category: 'Cardiology & Vascular',
    specialties: [
      'Cardiologist',
      'Interventional Cardiologist',
      'Invasive Cardiologist',
      'Non-Invasive Cardiologist',
      'Pediatric Cardiologist',
      'Electrophysiologist',
      'Heart Failure Specialist',
      'Advanced Heart Failure Specialist',
      'Preventive Cardiologist',
      'Cardiac Imaging Specialist',
      'Cardio-Oncologist',
      'Hypertension Specialist',
      'Cardiac Rehabilitation Specialist',
      'Cardiac Surgeon',
      'Vascular Surgeon',
      'Endovascular Surgeon',
      'Peripheral Vascular Specialist',
      'Phlebologist',
    ],
  },

  {
    category: 'Neurology & Neuroscience',
    specialties: [
      'Neurologist',
      'Pediatric Neurologist',
      'Behavioral Neurologist',
      'Cognitive Neurologist',
      'Vascular Neurologist',
      'Stroke Specialist',
      'Epileptologist',
      'Neurophysiologist',
      'Clinical Neurophysiologist',
      'Neuromuscular Specialist',
      'Movement Disorders Specialist',
      'Multiple Sclerosis Specialist',
      'Neuroimmunologist',
      'Headache Specialist',
      'Migraine Specialist',
      'Neuro-Oncologist',
      'Neurogeneticist',
      'Autonomic Neurologist',
      'Sleep Neurologist',
      'Neurocritical Care Specialist',
      'Neurorehabilitation Specialist',
    ],
  },

  {
    category: 'Neurosurgery',
    specialties: [
      'Neurosurgeon',
      'Pediatric Neurosurgeon',
      'Cerebrovascular Neurosurgeon',
      'Endovascular Neurosurgeon',
      'Skull Base Neurosurgeon',
      'Spinal Neurosurgeon',
      'Functional Neurosurgeon',
      'Epilepsy Neurosurgeon',
      'Neuro-Oncology Surgeon',
      'Trauma Neurosurgeon',
      'Peripheral Nerve Surgeon',
      'Stereotactic Neurosurgeon',
      'Neurovascular Surgeon',
    ],
  },

  {
    category: 'Orthopedics & Sports Medicine',
    specialties: [
      'Orthopedic Surgeon',
      'Orthopedic Physician',
      'Orthopedic Specialist',
      'Pediatric Orthopedic Surgeon',
      'Orthopedic Trauma Surgeon',
      'Orthopedic Spine Surgeon',
      'Spine Surgeon',
      'Sports Medicine Physician',
      'Sports Medicine Specialist',
      'Sports Orthopedic Surgeon',
      'Shoulder & Elbow Surgeon',
      'Hip & Knee Surgeon',
      'Foot & Ankle Surgeon',
      'Hand & Wrist Surgeon',
      'Joint Replacement Surgeon',
      'Arthroplasty Surgeon',
      'Arthroscopy Surgeon',
      'Knee Surgeon',
      'Shoulder Surgeon',
      'Hip Surgeon',
      'Foot & Ankle Specialist',
      'Hand Surgeon',
      'Wrist Surgeon',
      'Pediatric Sports Medicine Specialist',
      'Musculoskeletal Specialist',
      'Musculoskeletal Medicine Specialist',
      'Orthopedic Oncology Specialist',
      'Musculoskeletal Oncologist',
      'Sports Injury Specialist',
      'Sports Rehabilitation Specialist',
      'Exercise Medicine Specialist',
      'Rheumatologist',
      'Physiatrist',
      'Physical Medicine & Rehabilitation Specialist',
      'Osteoporosis Specialist',
    ],
  },

  {
    category: 'Surgery',
    specialties: [
      'General Surgeon',
      'Laparoscopic Surgeon',
      'Minimally Invasive Surgeon',
      'Robotic Surgeon',
      'Bariatric Surgeon',
      'Metabolic Surgeon',
      'Trauma Surgeon',
      'Acute Care Surgeon',
      'Emergency Surgeon',
      'Breast Surgeon',
      'Endocrine Surgeon',
      'Hernia Surgeon',
      'Colorectal Surgeon',
      'Gastrointestinal Surgeon',
      'Abdominal Surgeon',
      'Pediatric Surgeon',
      'Surgical Oncologist',
      'Transplant Surgeon',
    ],
  },

  {
    category: 'Cardiothoracic Surgery',
    specialties: [
      'Cardiothoracic Surgeon',
      'Cardiac Surgeon',
      'Thoracic Surgeon',
      'Pediatric Cardiac Surgeon',
      'Congenital Heart Surgeon',
      'Aortic Surgeon',
      'Valve Surgeon',
      'Coronary Artery Bypass Surgeon',
      'Lung Transplant Surgeon',
      'Thoracic Oncology Surgeon',
    ],
  },

  {
    category: 'Plastic, Reconstructive & Cosmetic Surgery',
    specialties: [
      'Plastic Surgeon',
      'Cosmetic Surgeon',
      'Aesthetic Surgeon',
      'Reconstructive Surgeon',
      'Craniofacial Surgeon',
      'Facial Plastic Surgeon',
      'Hand Plastic Surgeon',
      'Microsurgeon',
      'Burn Surgeon',
      'Breast Reconstruction Surgeon',
      'Maxillofacial Plastic Surgeon',
      'Gender Affirming Surgeon',
    ],
  },

  {
    category: 'Gastroenterology & Hepatology',
    specialties: [
      'Gastroenterologist',
      'Pediatric Gastroenterologist',
      'Hepatologist',
      'Transplant Hepatologist',
      'Interventional Gastroenterologist',
      'Advanced Endoscopist',
      'Endoscopist',
      'ERCP Specialist',
      'EUS Specialist',
      'Inflammatory Bowel Disease Specialist',
      'Motility Specialist',
      'Neurogastroenterologist',
      'Pancreatobiliary Specialist',
      'Colorectal Specialist',
      'Colorectal Surgeon',
    ],
  },

  {
    category: 'Pulmonology & Respiratory Medicine',
    specialties: [
      'Pulmonologist',
      'Respiratory Physician',
      'Pediatric Pulmonologist',
      'Interventional Pulmonologist',
      'Pulmonary Critical Care Specialist',
      'Critical Care Specialist',
      'Sleep Medicine Specialist',
      'Sleep Physician',
      'Pulmonary Hypertension Specialist',
      'Interstitial Lung Disease Specialist',
      'Cystic Fibrosis Specialist',
      'COPD Specialist',
      'Asthma Specialist',
      'Lung Transplant Specialist',
    ],
  },

  {
    category: 'Nephrology & Urology',
    specialties: [
      'Nephrologist',
      'Pediatric Nephrologist',
      'Transplant Nephrologist',
      'Dialysis Specialist',
      'Interventional Nephrologist',
      'Urologist',
      'Pediatric Urologist',
      'Urologic Oncologist',
      'Endourologist',
      'Reconstructive Urologist',
      'Female Urologist',
      'Andrologist',
      'Neurourologist',
      'Urogynecologist',
      'Robotic Urologic Surgeon',
      'Renal Transplant Surgeon',
      'Kidney Stone Specialist',
      'Male Infertility Specialist',
    ],
  },

  {
    category: 'Obstetrics, Gynecology & Fertility',
    specialties: [
      'Gynecologist',
      'Obstetrician',
      'Obstetrician & Gynecologist (OB/GYN)',
      'Maternal-Fetal Medicine Specialist',
      'Perinatologist',
      'Reproductive Endocrinologist',
      'IVF Specialist',
      'Fertility Specialist',
      'Reproductive Medicine Specialist',
      'Gynecologic Oncologist',
      'Urogynecologist',
      'Gynecologic Surgeon',
      'Minimally Invasive Gynecologic Surgeon',
      'Pediatric & Adolescent Gynecologist',
      'Menopause Specialist',
      'High-Risk Pregnancy Specialist',
      'Prenatal Medicine Specialist',
      'Family Planning Specialist',
      'Reproductive Surgeon',
      'Breast Health Specialist',
    ],
  },

  {
    category: 'Pediatrics & Child Health',
    specialties: [
      'Pediatrician',
      'General Pediatrician',
      'Pediatric Emergency Medicine Specialist',
      'Pediatric Intensive Care Specialist',
      'Pediatric Cardiologist',
      'Pediatric Neurologist',
      'Pediatric Neurosurgeon',
      'Pediatric Gastroenterologist',
      'Pediatric Hepatologist',
      'Pediatric Pulmonologist',
      'Pediatric Nephrologist',
      'Pediatric Urologist',
      'Pediatric Endocrinologist',
      'Pediatric Rheumatologist',
      'Pediatric Allergist',
      'Pediatric Immunologist',
      'Pediatric Infectious Disease Specialist',
      'Pediatric Hematologist',
      'Pediatric Oncologist',
      'Pediatric Dermatologist',
      'Pediatric Ophthalmologist',
      'Pediatric ENT Specialist',
      'Pediatric Orthopedic Surgeon',
      'Pediatric Surgeon',
      'Pediatric Cardiothoracic Surgeon',
      'Developmental Pediatrician',
      'Adolescent Medicine Specialist',
      'Child Abuse Pediatrician',
      'Pediatric Rehabilitation Specialist',
    ],
  },

  {
    category: 'Neonatology & Perinatal Medicine',
    specialties: [
      'Neonatologist',
      'Neonatal Intensive Care Specialist',
      'Neonatal Surgeon',
      'Neonatal Cardiologist',
      'Neonatal Neurologist',
      'Neonatal Pulmonologist',
      'Neonatal Nutrition Specialist',
      'Neonatal Critical Care Specialist',
      'Neonatal Transport Specialist',
      'Perinatologist',
    ],
  },

  {
    category: 'Oncology & Cancer Medicine',
    specialties: [
      'Medical Oncologist',
      'Clinical Oncologist',
      'Radiation Oncologist',
      'Surgical Oncologist',
      'Pediatric Oncologist',
      'Neuro-Oncologist',
      'Gynecologic Oncologist',
      'Urologic Oncologist',
      'Breast Oncologist',
      'Thoracic Oncologist',
      'Gastrointestinal Oncologist',
      'Genitourinary Oncologist',
      'Head & Neck Oncologist',
      'Musculoskeletal Oncologist',
      'Hematologic Oncologist',
      'Interventional Oncology Specialist',
      'Cancer Genetics Specialist',
      'Cancer Pain Specialist',
      'Palliative Oncology Specialist',
    ],
  },

  {
    category: 'Hematology & Blood Disorders',
    specialties: [
      'Hematologist',
      'Clinical Hematologist',
      'Hematologic Oncologist',
      'Pediatric Hematologist',
      'Hematopathologist',
      'Transfusion Medicine Specialist',
      'Blood Banking Specialist',
      'Coagulation Specialist',
      'Hemophilia Specialist',
      'Sickle Cell Specialist',
      'Bone Marrow Transplant Specialist',
      'Stem Cell Transplant Specialist',
      'Cell Therapy Specialist',
    ],
  },

  {
    category: 'Endocrinology & Metabolism',
    specialties: [
      'Endocrinologist',
      'Diabetologist',
      'Pediatric Endocrinologist',
      'Thyroid Specialist',
      'Adrenal Specialist',
      'Pituitary Specialist',
      'Reproductive Endocrinologist',
      'Metabolic Disease Specialist',
      'Bone & Mineral Metabolism Specialist',
      'Osteoporosis Specialist',
      'Obesity Medicine Specialist',
      'Lipid Specialist',
    ],
  },

  {
    category: 'Dermatology & Aesthetics',
    specialties: [
      'Dermatologist',
      'Medical Dermatologist',
      'Cosmetic Dermatologist',
      'Pediatric Dermatologist',
      'Dermatopathologist',
      'Dermato-Surgeon',
      'Dermatologic Surgeon',
      'Mohs Surgeon',
      'Aesthetic Dermatologist',
      'Hair & Scalp Specialist',
      'Trichologist',
      'Contact Dermatitis Specialist',
      'Immunodermatologist',
      'Photodermatologist',
      'Laser Dermatologist',
      'Venereologist',
    ],
  },

  {
    category: 'ENT & Otolaryngology',
    specialties: [
      'ENT Specialist',
      'ENT Specialist (Otolaryngologist)',
      'Otolaryngologist',
      'Head & Neck Surgeon',
      'Pediatric ENT Specialist',
      'Otologist',
      'Neurotologist',
      'Rhinologist',
      'Sinus Specialist',
      'Laryngologist',
      'Voice Specialist',
      'Sleep Surgery Specialist',
      'Head & Neck Oncologic Surgeon',
      'Facial Plastic Surgeon',
      'Skull Base ENT Surgeon',
      'Otology Surgeon',
    ],
  },

  {
    category: 'Ophthalmology & Eye Care',
    specialties: [
      'Ophthalmologist',
      'Pediatric Ophthalmologist',
      'Retina Specialist',
      'Vitreoretinal Surgeon',
      'Cornea Specialist',
      'Corneal Surgeon',
      'Glaucoma Specialist',
      'Cataract Surgeon',
      'Refractive Surgeon',
      'LASIK Surgeon',
      'Oculoplastic Surgeon',
      'Neuro-Ophthalmologist',
      'Uveitis Specialist',
      'Ocular Oncology Specialist',
      'Ophthalmic Plastic Surgeon',
      'Low Vision Specialist',
      'Optometrist',
      'Orthoptist',
      'Optician',
    ],
  },

  {
    category: 'Dentistry & Oral Health',
    specialties: [
      'General Dentist',
      'Family Dentist',
      'Pediatric Dentist',
      'Dental Surgeon',
      'Endodontist',
      'Periodontist',
      'Prosthodontist',
      'Orthodontist',
      'Oral & Maxillofacial Surgeon',
      'Oral Medicine Specialist',
      'Oral Pathologist',
      'Cosmetic Dentist',
      'Restorative Dentist',
      'Implant Dentist',
      'Geriatric Dentist',
      'Special Needs Dentist',
      'Public Health Dentist',
      'Dental Radiologist',
      'Maxillofacial Prosthodontist',
      'Craniofacial Prosthodontist',
      'TMJ Specialist',
      'Dental Sleep Medicine Specialist',
      'Dental Hygienist',
      'Dental Technician',
    ],
  },

  {
    category: 'Psychiatry & Behavioral Health',
    specialties: [
      'Psychiatrist',
      'General Psychiatrist',
      'Child & Adolescent Psychiatrist',
      'Geriatric Psychiatrist',
      'Addiction Psychiatrist',
      'Forensic Psychiatrist',
      'Consultation-Liaison Psychiatrist',
      'Emergency Psychiatrist',
      'Neuropsychiatrist',
      'Perinatal Psychiatrist',
      'Sleep Psychiatrist',
      'Clinical Psychologist',
      'Counseling Psychologist',
      'Neuropsychologist',
      'Forensic Psychologist',
      'Health Psychologist',
      'Rehabilitation Psychologist',
      'School Psychologist',
      'Child Psychologist',
      'Behavioral Therapist',
      'Psychotherapist',
      'Marriage & Family Therapist',
      'Mental Health Counselor',
      'Addiction Counselor',
    ],
  },

  {
    category: 'Infectious Diseases & Immunology',
    specialties: [
      'Infectious Diseases Specialist',
      'Pediatric Infectious Diseases Specialist',
      'Immunologist',
      'Allergist',
      'Immunologist / Allergist',
      'HIV Specialist',
      'Tropical Medicine Specialist',
      'Tropical Medicine',
      'Travel Medicine Specialist',
      'Hospital Infection Control Specialist',
      'Antimicrobial Stewardship Specialist',
      'Vaccine Specialist',
      'Clinical Immunologist',
      'Autoimmune Disease Specialist',
      'Immunodeficiency Specialist',
      'Food Allergy Specialist',
      'Drug Allergy Specialist',
      'Environmental Allergy Specialist',
    ],
  },

  {
    category: 'Radiology & Imaging',
    specialties: [
      'Radiologist',
      'Diagnostic Radiologist',
      'Interventional Radiologist',
      'Pediatric Radiologist',
      'Neuroradiologist',
      'Musculoskeletal Radiologist',
      'Abdominal Radiologist',
      'Cardiothoracic Radiologist',
      'Breast Radiologist',
      'Emergency Radiologist',
      'Nuclear Medicine Specialist',
      'Nuclear Radiologist',
      'Molecular Imaging Specialist',
      'Interventional Oncology Radiologist',
      'Ultrasonologist',
      'Medical Imaging Specialist',
    ],
  },

  {
    category: 'Pathology & Laboratory Medicine',
    specialties: [
      'Pathologist',
      'Anatomic Pathologist',
      'Clinical Pathologist',
      'Hematopathologist',
      'Dermatopathologist',
      'Neuropathologist',
      'Forensic Pathologist',
      'Pediatric Pathologist',
      'Molecular Pathologist',
      'Surgical Pathologist',
      'Cytopathologist',
      'Histopathologist',
      'Chemical Pathologist',
      'Clinical Biochemist',
      'Medical Microbiologist',
      'Clinical Microbiologist',
      'Virologist',
      'Bacteriologist',
      'Mycologist',
      'Parasitologist',
      'Immunopathologist',
      'Transfusion Medicine Specialist',
      'Blood Bank Specialist',
      'Genetic Pathologist',
    ],
  },

  {
    category: 'Anesthesia & Pain Medicine',
    specialties: [
      'Anesthesiologist',
      'General Anesthesiologist',
      'Cardiac Anesthesiologist',
      'Pediatric Anesthesiologist',
      'Neuroanesthesiologist',
      'Obstetric Anesthesiologist',
      'Regional Anesthesiologist',
      'Ambulatory Anesthesiologist',
      'Critical Care Anesthesiologist',
      'Pain Management Specialist',
      'Pain Medicine Specialist',
      'Acute Pain Specialist',
      'Chronic Pain Specialist',
      'Interventional Pain Specialist',
      'Cancer Pain Specialist',
      'Pediatric Pain Specialist',
    ],
  },

  {
    category: 'Critical Care & Intensive Care',
    specialties: [
      'Critical Care Specialist',
      'Intensivist',
      'Medical Intensivist',
      'Surgical Intensivist',
      'Neurocritical Care Specialist',
      'Cardiac Critical Care Specialist',
      'Pediatric Intensivist',
      'Neonatal Intensivist',
      'Trauma Critical Care Specialist',
      'Burn Intensive Care Specialist',
      'Transplant Critical Care Specialist',
      'Emergency Critical Care Specialist',
    ],
  },

  {
    category: 'Emergency & Acute Care',
    specialties: [
      'Emergency Medicine Physician',
      'Pediatric Emergency Physician',
      'Emergency Trauma Physician',
      'Emergency Critical Care Specialist',
      'Toxicology Specialist',
      'Medical Toxicologist',
      'Wilderness Medicine Specialist',
      'Disaster Medicine Specialist',
      'Prehospital Emergency Medicine Specialist',
      'Air Ambulance Medicine Specialist',
      'Hyperbaric Medicine Specialist',
      'Sports Emergency Medicine Specialist',
    ],
  },

  {
    category: 'Physical Medicine & Rehabilitation',
    specialties: [
      'Physiatrist',
      'Physical Medicine & Rehabilitation Specialist',
      'Rehabilitation Medicine Specialist',
      'Neurological Rehabilitation Specialist',
      'Musculoskeletal Rehabilitation Specialist',
      'Pediatric Rehabilitation Specialist',
      'Cardiac Rehabilitation Specialist',
      'Pulmonary Rehabilitation Specialist',
      'Spinal Cord Injury Specialist',
      'Brain Injury Rehabilitation Specialist',
      'Amputee Rehabilitation Specialist',
      'Pain Rehabilitation Specialist',
      'Sports Rehabilitation Specialist',
    ],
  },

  {
    category: 'Physiotherapy & Physical Therapy',
    specialties: [
      'Physiotherapist',
      'Physical Therapist',
      'Musculoskeletal Physiotherapist',
      'Orthopedic Physiotherapist',
      'Sports Physiotherapist',
      'Neurological Physiotherapist',
      'Pediatric Physiotherapist',
      'Geriatric Physiotherapist',
      'Cardiopulmonary Physiotherapist',
      'Women’s Health Physiotherapist',
      'Pelvic Floor Physiotherapist',
      'Vestibular Physiotherapist',
      'Hand Therapist',
      'Manual Therapist',
      'Aquatic Therapist',
      'Rehabilitation Therapist',
    ],
  },

  {
    category: 'Occupational Therapy',
    specialties: [
      'Occupational Therapist',
      'Pediatric Occupational Therapist',
      'Neurological Occupational Therapist',
      'Hand Occupational Therapist',
      'Mental Health Occupational Therapist',
      'Geriatric Occupational Therapist',
      'Rehabilitation Occupational Therapist',
      'Sensory Integration Therapist',
      'Assistive Technology Specialist',
    ],
  },

  {
    category: 'Speech, Language & Audiology',
    specialties: [
      'Speech-Language Pathologist',
      'Speech Therapist',
      'Speech & Language Therapist',
      'Pediatric Speech Therapist',
      'Neurological Speech Therapist',
      'Voice Therapist',
      'Swallowing Therapist',
      'Dysphagia Specialist',
      'Audiologist',
      'Pediatric Audiologist',
      'Clinical Audiologist',
      'Hearing Rehabilitation Specialist',
      'Vestibular Audiologist',
    ],
  },

  {
    category: 'Nursing',
    specialties: [
      'Registered Nurse',
      'Licensed Practical Nurse',
      'Licensed Vocational Nurse',
      'Nurse Practitioner',
      'Family Nurse Practitioner',
      'Adult-Gerontology Nurse Practitioner',
      'Pediatric Nurse Practitioner',
      'Acute Care Nurse Practitioner',
      'Psychiatric Mental Health Nurse Practitioner',
      'Women’s Health Nurse Practitioner',
      'Neonatal Nurse Practitioner',
      'Emergency Nurse',
      'Critical Care Nurse',
      'ICU Nurse',
      'CCU Nurse',
      'Operating Room Nurse',
      'Surgical Nurse',
      'Pediatric Nurse',
      'Neonatal Nurse',
      'Oncology Nurse',
      'Hematology Nurse',
      'Cardiology Nurse',
      'Neurology Nurse',
      'Orthopedic Nurse',
      'Dialysis Nurse',
      'Transplant Nurse',
      'Wound Care Nurse',
      'Pain Management Nurse',
      'Palliative Care Nurse',
      'Hospice Nurse',
      'Geriatric Nurse',
      'Community Health Nurse',
      'Public Health Nurse',
      'School Nurse',
      'Occupational Health Nurse',
      'Infection Control Nurse',
      'Nurse Anesthetist',
      'Nurse Midwife',
      'Clinical Nurse Specialist',
      'Nurse Educator',
      'Nurse Researcher',
    ],
  },

  {
    category: 'Midwifery',
    specialties: [
      'Midwife',
      'Certified Midwife',
      'Certified Nurse Midwife',
      'Registered Midwife',
      'Community Midwife',
      'Hospital Midwife',
      'Maternal Care Midwife',
      'Birth Center Midwife',
      'Postnatal Midwife',
      'Lactation Midwife',
    ],
  },

  {
    category: 'Pharmacy & Pharmaceutical Medicine',
    specialties: [
      'Pharmacist',
      'Clinical Pharmacist',
      'Hospital Pharmacist',
      'Community Pharmacist',
      'Retail Pharmacist',
      'Industrial Pharmacist',
      'Compounding Pharmacist',
      'Oncology Pharmacist',
      'Pediatric Pharmacist',
      'Geriatric Pharmacist',
      'Psychiatric Pharmacist',
      'Nuclear Pharmacist',
      'Critical Care Pharmacist',
      'Infectious Disease Pharmacist',
      'Anticoagulation Pharmacist',
      'Ambulatory Care Pharmacist',
      'Pharmacy Informatics Specialist',
      'Pharmacovigilance Specialist',
      'Pharmaceutical Scientist',
      'Pharmacy Technician',
    ],
  },

  {
    category: 'Nutrition & Dietetics',
    specialties: [
      'Dietitian',
      'Registered Dietitian',
      'Clinical Dietitian',
      'Sports Dietitian',
      'Pediatric Dietitian',
      'Renal Dietitian',
      'Diabetes Dietitian',
      'Oncology Dietitian',
      'Critical Care Dietitian',
      'Geriatric Dietitian',
      'Community Dietitian',
      'Public Health Nutritionist',
      'Clinical Nutritionist',
      'Nutrition Specialist',
      'Metabolic Nutrition Specialist',
      'Eating Disorder Dietitian',
    ],
  },

  {
    category: 'Genetics & Genomic Medicine',
    specialties: [
      'Medical Geneticist',
      'Clinical Geneticist',
      'Genetic Counselor',
      'Genomic Medicine Specialist',
      'Cancer Geneticist',
      'Pediatric Geneticist',
      'Neurogeneticist',
      'Metabolic Geneticist',
      'Prenatal Geneticist',
      'Molecular Geneticist',
      'Clinical Genomics Specialist',
      'Pharmacogenomics Specialist',
      'Cytogeneticist',
      'Genomic Pathologist',
    ],
  },

  {
    category: 'Laboratory & Biomedical Sciences',
    specialties: [
      'Medical Laboratory Scientist',
      'Medical Laboratory Technologist',
      'Medical Laboratory Technician',
      'Clinical Laboratory Scientist',
      'Clinical Laboratory Technologist',
      'Medical Technologist',
      'Histotechnologist',
      'Histology Technician',
      'Cytotechnologist',
      'Phlebotomist',
      'Medical Microbiologist',
      'Clinical Biochemist',
      'Molecular Biologist',
      'Molecular Diagnostics Specialist',
      'Immunology Laboratory Specialist',
      'Hematology Laboratory Specialist',
      'Blood Bank Technologist',
      'Transfusion Scientist',
      'Genetics Laboratory Specialist',
      'Pathology Assistant',
    ],
  },

  {
    category: 'Radiography & Imaging Technology',
    specialties: [
      'Radiologic Technologist',
      'Radiographer',
      'Diagnostic Radiographer',
      'CT Technologist',
      'MRI Technologist',
      'Mammography Technologist',
      'Interventional Radiology Technologist',
      'Nuclear Medicine Technologist',
      'PET Technologist',
      'Ultrasound Technologist',
      'Sonographer',
      'Cardiac Sonographer',
      'Vascular Sonographer',
      'Echocardiographer',
      'Radiation Therapy Technologist',
      'Dosimetrist',
      'Radiation Therapist',
    ],
  },

  {
    category: 'Respiratory Therapy',
    specialties: [
      'Respiratory Therapist',
      'Respiratory Care Practitioner',
      'Pulmonary Function Technologist',
      'Sleep Technologist',
      'Polysomnography Technologist',
      'Neonatal Respiratory Therapist',
      'Pediatric Respiratory Therapist',
      'Critical Care Respiratory Therapist',
      'Cardiopulmonary Technologist',
    ],
  },

  {
    category: 'Prosthetics & Orthotics',
    specialties: [
      'Prosthetist',
      'Orthotist',
      'Prosthetist-Orthotist',
      'Clinical Prosthetist',
      'Clinical Orthotist',
      'Pediatric Orthotist',
      'Spinal Orthotist',
      'Upper Limb Prosthetist',
      'Lower Limb Prosthetist',
      'Rehabilitation Prosthetist',
      'Assistive Device Specialist',
    ],
  },

  {
    category: 'Podiatry & Foot Medicine',
    specialties: [
      'Podiatrist',
      'Podiatric Surgeon',
      'Pediatric Podiatrist',
      'Sports Podiatrist',
      'Diabetic Foot Specialist',
      'Podiatric Orthopedist',
      'Foot & Ankle Specialist',
      'Podiatric Wound Care Specialist',
    ],
  },

  {
    category: 'Palliative & Hospice Medicine',
    specialties: [
      'Palliative Care Specialist',
      'Palliative Medicine Physician',
      'Hospice Physician',
      'Hospice Nurse',
      'Pediatric Palliative Care Specialist',
      'Geriatric Palliative Care Specialist',
      'Oncology Palliative Care Specialist',
      'End-of-Life Care Specialist',
      'Bereavement Counselor',
      'Hospice Social Worker',
    ],
  },

  {
    category: 'Geriatric Medicine',
    specialties: [
      'Geriatrician',
      'Geriatric Medicine Specialist',
      'Geriatric Psychiatrist',
      'Geriatric Cardiologist',
      'Geriatric Neurologist',
      'Geriatric Oncologist',
      'Geriatric Rehabilitation Specialist',
      'Geriatric Pharmacist',
      'Geriatric Nurse',
      'Geriatric Dietitian',
    ],
  },

  {
    category: 'Forensic & Legal Medicine',
    specialties: [
      'Forensic Physician',
      'Forensic Pathologist',
      'Forensic Psychiatrist',
      'Forensic Psychologist',
      'Clinical Forensic Specialist',
      'Forensic Toxicologist',
      'Forensic Odontologist',
      'Medical Examiner',
      'Coroner',
      'Medicolegal Specialist',
      'Sexual Assault Examiner',
      'Forensic Nurse Examiner',
    ],
  },

  {
    category: 'Toxicology',
    specialties: [
      'Medical Toxicologist',
      'Clinical Toxicologist',
      'Emergency Toxicologist',
      'Occupational Toxicologist',
      'Forensic Toxicologist',
      'Environmental Toxicologist',
      'Pharmaceutical Toxicologist',
      'Poison Control Specialist',
    ],
  },

  {
    category: 'Sports Medicine',
    specialties: [
      'Sports Medicine Physician',
      'Sports Medicine Surgeon',
      'Sports Cardiologist',
      'Sports Orthopedic Surgeon',
      'Sports Physiotherapist',
      'Sports Rehabilitation Specialist',
      'Sports Nutritionist',
      'Exercise Medicine Specialist',
      'Exercise Physiologist',
      'Team Physician',
      'Athletic Trainer',
    ],
  },

  {
    category: 'Public Health & Preventive Medicine',
    specialties: [
      'Public Health Specialist',
      'Public Health Physician',
      'Community Medicine Specialist',
      'Epidemiologist',
      'Clinical Epidemiologist',
      'Infectious Disease Epidemiologist',
      'Field Epidemiologist',
      'Environmental Health Specialist',
      'Occupational Health Specialist',
      'Global Health Specialist',
      'Health Policy Specialist',
      'Health Promotion Specialist',
      'Disease Prevention Specialist',
      'Maternal & Child Health Specialist',
      'Population Health Specialist',
      'Health Educator',
      'Biostatistician',
    ],
  },

  {
    category: 'Occupational & Environmental Medicine',
    specialties: [
      'Occupational Medicine Physician',
      'Occupational Health Specialist',
      'Industrial Medicine Specialist',
      'Aerospace Medicine Specialist',
      'Maritime Medicine Specialist',
      'Environmental Medicine Specialist',
      'Environmental Health Specialist',
      'Workplace Health Specialist',
      'Occupational Rehabilitation Specialist',
      'Ergonomics Specialist',
    ],
  },

  {
    category: 'Sexual & Reproductive Health',
    specialties: [
      'Sexual Medicine Specialist',
      'Sexologist',
      'Andrologist',
      'Reproductive Endocrinologist',
      'Fertility Specialist',
      'IVF Specialist',
      'Male Infertility Specialist',
      'Female Infertility Specialist',
      'Sexual Health Physician',
      'Sexual Dysfunction Specialist',
      'Reproductive Health Specialist',
      'Family Planning Specialist',
      'Contraception Specialist',
    ],
  },

  {
    category: 'Transplant Medicine',
    specialties: [
      'Transplant Physician',
      'Transplant Surgeon',
      'Kidney Transplant Specialist',
      'Liver Transplant Specialist',
      'Heart Transplant Specialist',
      'Lung Transplant Specialist',
      'Pancreas Transplant Specialist',
      'Bone Marrow Transplant Specialist',
      'Stem Cell Transplant Specialist',
      'Transplant Nephrologist',
      'Transplant Hepatologist',
      'Transplant Infectious Disease Specialist',
      'Transplant Pharmacist',
      'Transplant Coordinator',
      'Transplant Immunologist',
    ],
  },

  {
    category: 'Wound Care',
    specialties: [
      'Wound Care Physician',
      'Wound Care Specialist',
      'Wound Care Nurse',
      'Diabetic Wound Specialist',
      'Chronic Wound Specialist',
      'Pressure Injury Specialist',
      'Burn Wound Specialist',
      'Vascular Wound Specialist',
      'Podiatric Wound Specialist',
      'Hyperbaric Medicine Specialist',
    ],
  },

  {
    category: 'Burn Medicine',
    specialties: [
      'Burn Surgeon',
      'Burn Physician',
      'Burn Specialist',
      'Burn Intensive Care Specialist',
      'Burn Rehabilitation Specialist',
      'Burn Wound Specialist',
      'Burn Nurse',
      'Burn Rehabilitation Therapist',
    ],
  },

  {
    category: 'Sleep Medicine',
    specialties: [
      'Sleep Medicine Physician',
      'Sleep Specialist',
      'Pediatric Sleep Specialist',
      'Neurological Sleep Specialist',
      'Respiratory Sleep Specialist',
      'Sleep Psychiatrist',
      'Sleep Psychologist',
      'Sleep Technologist',
      'Polysomnography Technologist',
      'Behavioral Sleep Medicine Specialist',
    ],
  },

  {
    category: 'Hyperbaric & Diving Medicine',
    specialties: [
      'Hyperbaric Medicine Specialist',
      'Diving Medicine Specialist',
      'Undersea Medicine Specialist',
      'Wound Hyperbaric Specialist',
      'Hyperbaric Technician',
    ],
  },

  {
    category: 'Aerospace & Aviation Medicine',
    specialties: [
      'Aerospace Medicine Specialist',
      'Aviation Medicine Specialist',
      'Flight Surgeon',
      'Space Medicine Specialist',
      'Aviation Medical Examiner',
      'Aeromedical Specialist',
    ],
  },

  {
    category: 'Disaster, Military & Tactical Medicine',
    specialties: [
      'Disaster Medicine Specialist',
      'Military Physician',
      'Military Surgeon',
      'Military Psychiatrist',
      'Combat Medicine Specialist',
      'Tactical Medicine Specialist',
      'Field Medicine Specialist',
      'Disaster Response Specialist',
      'Emergency Preparedness Specialist',
      'Humanitarian Medicine Specialist',
    ],
  },

  {
    category: 'Complementary & Alternative Medicine',
    specialties: [
      'Homeopath',
      'Ayurvedic Practitioner',
      'Ayurvedic Physician',
      'Traditional Chinese Medicine Practitioner',
      'Acupuncturist',
      'Naturopathic Physician',
      'Osteopathic Physician',
      'Chiropractor',
      'Traditional Medicine Practitioner',
      'Herbal Medicine Practitioner',
      'Unani Medicine Practitioner',
      'Hijama Practitioner',
      'Cupping Therapy Practitioner',
      'Complementary Medicine Specialist',
      'Integrative Medicine Specialist',
    ],
  },

  {
    category: 'Healthcare Social Work & Case Management',
    specialties: [
      'Medical Social Worker',
      'Clinical Social Worker',
      'Hospital Social Worker',
      'Pediatric Social Worker',
      'Oncology Social Worker',
      'Psychiatric Social Worker',
      'Geriatric Social Worker',
      'Hospice Social Worker',
      'Case Manager',
      'Clinical Case Manager',
      'Care Coordinator',
      'Patient Navigator',
      'Discharge Planner',
      'Healthcare Advocate',
    ],
  },

  {
    category: 'Healthcare Administration & Management',
    specialties: [
      'Healthcare Administrator',
      'Hospital Administrator',
      'Healthcare Manager',
      'Clinical Manager',
      'Medical Director',
      'Nursing Director',
      'Healthcare Operations Manager',
      'Healthcare Quality Manager',
      'Patient Safety Specialist',
      'Healthcare Compliance Specialist',
      'Healthcare Risk Manager',
      'Medical Records Manager',
      'Health Information Manager',
      'Clinical Documentation Specialist',
      'Healthcare Accreditation Specialist',
    ],
  },

  {
    category: 'Health Informatics & Digital Health',
    specialties: [
      'Health Informatics Specialist',
      'Clinical Informatics Specialist',
      'Medical Informatics Specialist',
      'Nursing Informatics Specialist',
      'Pharmacy Informatics Specialist',
      'Bioinformatics Specialist',
      'Clinical Data Scientist',
      'Healthcare Data Analyst',
      'Healthcare Data Scientist',
      'Medical AI Specialist',
      'Digital Health Specialist',
      'Telemedicine Specialist',
      'Telehealth Specialist',
      'Clinical Systems Specialist',
      'Health Information Technologist',
    ],
  },

  {
    category: 'Biomedical Engineering & Medical Technology',
    specialties: [
      'Biomedical Engineer',
      'Clinical Engineer',
      'Medical Device Specialist',
      'Biomedical Equipment Technician',
      'Clinical Technology Specialist',
      'Medical Imaging Engineer',
      'Rehabilitation Engineer',
      'Prosthetics Engineer',
      'Biomaterials Specialist',
      'Tissue Engineering Specialist',
      'Medical Robotics Specialist',
      'Healthcare Technology Specialist',
    ],
  },

  {
    category: 'Medical Research & Clinical Trials',
    specialties: [
      'Clinical Researcher',
      'Clinical Research Physician',
      'Clinical Trial Specialist',
      'Clinical Research Coordinator',
      'Clinical Research Associate',
      'Research Nurse',
      'Research Pharmacist',
      'Translational Medicine Specialist',
      'Biomedical Researcher',
      'Medical Scientist',
      'Epidemiology Researcher',
      'Public Health Researcher',
      'Medical Statistician',
      'Biostatistician',
      'Research Methodologist',
      'Clinical Data Manager',
      'Regulatory Affairs Specialist',
    ],
  },

  {
    category: 'Medical Education',
    specialties: [
      'Medical Educator',
      'Clinical Educator',
      'Medical Teacher',
      'Medical Lecturer',
      'Medical Professor',
      'Clinical Skills Instructor',
      'Medical Simulation Specialist',
      'Medical Education Specialist',
      'Nursing Educator',
      'Pharmacy Educator',
      'Dental Educator',
      'Allied Health Educator',
    ],
  },

  {
    category: 'Other Healthcare Professions',
    specialties: [
      'Paramedic',
      'Emergency Medical Technician',
      'Medical Assistant',
      'Healthcare Assistant',
      'Patient Care Assistant',
      'Medical Scribe',
      'Clinical Coder',
      'Medical Transcriptionist',
      'Health Inspector',
      'Public Health Inspector',
      'Sterile Processing Technician',
      'Operating Room Technician',
      'Surgical Technologist',
      'Cardiovascular Technologist',
      'Perfusionist',
      'Clinical Perfusionist',
      'ECG Technician',
      'EEG Technician',
      'EMG Technician',
      'Neurodiagnostic Technologist',
      'Medical Equipment Technician',
    ],
  },

  {
    category: 'Other Specialties',
    specialties: [
      'Nephrology Dialysis Specialist',
      'Occupational Medicine',
      'Public Health Specialist',
      'Geneticist',
      'Palliative Care Specialist',
      'Sexologist',
      'Homeopath',
      'Other',
    ],
  },
];

/**
 * Default specialty.
 */
export const DEFAULT_SPECIALTY = 'General Physician';

/**
 * Flat list of all specialty values (for validation).
 */
export const ALL_SPECIALTIES = SPECIALTY_CATEGORIES.flatMap(
  (c) => c.specialties
);